version: '3'

services:
  piveau-hub-ui:
    build:
      context: ./piveau-hub-ui
      dockerfile: Dockerfile
    container_name: piveau-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  possible-x-signing-service:
    build:
      context: ./possible-x-signing-service
      dockerfile: Dockerfile
    container_name: possible-x-signing-service
    logging:
      options:
        max-size: "50m"
    ports:
      - "2020:2020"
    environment:
      - FLASK_PRIVATE_KEY=${FLASK_PRIVATE_KEY}

  piveau-hub-repo:
    image: dockerhub.fokus.fraunhofer.de:5000/piveau/hub/piveau-hub-repo:latest
    logging:
      options:
        max-size: "50m"
    ports:
      - 8081:8080
      - 8085:8085
      - 5002:5000
    environment:
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_HUB_SHELL_CONFIG={"http":{},"telnet":{}}
      - PIVEAU_TRIPLESTORE_CONFIG={"address":"http://virtuoso:8890","clearGeoDataCatalogues":["*"]}
      - PIVEAU_HUB_VALIDATOR={"enabled":true,"metricsPipeName":"metrics","history":false}
      - PIVEAU_HUB_SEARCH_SERVICE={"enabled":true,"url":"piveau-hub-search","port":8080,"api_key":"yourSearchApiKey"}
      - PIVEAU_FEATURE_FLAGS={"piveau_profile":true}
      - PIVEAU_PROFILE={"type":"directory","path":"/path/to/my/profile/my-profile"}
      - PIVEAU_TRUST_CONFIG={"did":"<Organization's did>","addressSignService":"<url of signing service>"}
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./pipes:/usr/verticles/pipes

  piveau-hub-search:
    image: registry.gitlab.com/piveau/hub/piveau-hub-search:5.0.3
    container_name: piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 8084:8080
      - 8086:8081
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_HUB_SEARCH_ES_CONFIG={"host":"elasticsearch","port":9200}
      - PIVEAU_HUB_SEARCH_GAZETTEER_CONFIG={"url":"http://doesnotmatter.eu"}
      - PIVEAU_FEATURE_FLAGS={"piveau_profile":true}
      - PIVEAU_PROFILE={"type":"directory","path":"/path/to/my/profile/my-profile"}
      - JAVA_OPTS=-Xms1g -Xmx2g

  virtuoso:
    image:  openlink/virtuoso-opensource-7:7.2.9
    container_name: virtuoso
    logging:
      options:
        max-size: "50m"
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=170000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=130000
      - VIRT_PARAMETERS_SERVERTHREADS=100
      - VIRT_HTTPSERVER_SERVERTHREADS=100
      - VIRT_HTTPSERVER_MAXCLIENTCONNECTIONS=100
    volumes:
      - virtuoso-data:/database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  virtuoso-data:
  elasticsearch-data: