stages:
  - build
  - register

build-asset:
  stage: build
  image: node:20-alpine
  only:
    - master
    - develop
    - tags
  script:
    - npm ci
    - cp config/user-config.sample.js config/user-config.js
    - npm run build
  artifacts:
    paths:
      - dist

register develop as latest:
  stage: register
  tags:
    - dind
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - develop
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE":latest .
    - docker push "$CI_REGISTRY_IMAGE":latest